####################
## varibales/apps ##
####################

$notes = obsidian
$mainMod = SUPER
$terminal = kitty
$imageEditor = gimp
$fileManager = dolphin
$menu = wofi
$browser = firefox

###############
## shortcuts ##
###############

bind = $mainMod, B, exec, $browser,
bind = $mainMod, O, exec, $notes,
bind = $mainMod, Q, exec, $terminal,
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown > /dev/null 2>$1 $$ hyprshutdown || huprctl dispatch exit
bind = $mainMod, E, exec, $fileManager,
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod,
bind = $mainMod,
bind = $mainMod,

exec-once = waybar

input {
  kb_layout = br
  kb_variant = abnt2
  }
