##############
## MONITORS ##
##############

monitor = eDP-1, 1366x768@59.99900,0x0,1
monitor = HDMI-A-1,1920x1080@120.00,1366x0,1
layerrule = match:namespace swaync-control-center, blur on,
layerrule = match:namespace swaync-control-center, ignore_alpha 0.2,
###################
## LOOK AND FEEL ##
###################

general {
        resize_on_border = true

        layout = dwindle
        gaps_in = 5
        gaps_out = 2, 10, 10, 10
        border_size = 2
        layout = dwindle
}

decoration {
        screen_shader =
        blur {
                enabled = true
                size = 10
                noise = 0
                passes = 2
                contrast = 1
                brightness = 0.95
                vibrancy = 1.0
        }
}
##############
## KEYBORAD ##
##############
input{
        kb_layout = br
        kb_variant = abnt2
}
####################
## variables/apps ##
####################

$moveto1 = command -v hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 1 && hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispaych workspace 2
$moveto2 = command -v hyprctl dispatch fucusmonitor HDMI-A-1 && hyprctl dispatch workspace 4 && hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 3
$moveto3 = command -v hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 5 && hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 6
$moveto4 = command -v hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 7 && hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 8
$notes = obsidian
$mainMod = SUPER
$terminal = kitty
$imageEditor = gimp
$fileManager = dolphin
$menu = wofi
$browser = firefox
$noteBar = swaync

###############
## shortcuts ##
###############

#---workspace---
bind = $mainMod, 1, exec, $moveto1
bind = $mainMod, 2, exec, $moveto2
bind = $mainMod, 3, exec, $moveto3
bind = $mainMod, 4, exec, $moveto4

#---window position---
#bind = $mainMod SHIFT, left, swapwindow, l
#bind = $mainMod SHIFT, right, swapwindow, r
#bind = $mainMod SHIFT, up, swapwindow, u
#bind = $mainMod SHIFT, down, swapwindow, d

bind = $mainMod SHIFT, right, exec, hyprctl dispatch movetoworkspace +2
bind = $mainMod SHIFT, left, exec, hyprctl dispatch movetoworkspace -2

bind = $mainMod, left, movewindow, mon:+1
bind = $mainMod, right, movewindow, mon:-1

bind = CTRL, left, resizeactive, -60 0
bind = CTRL, right, resizeactive, 60 0
bind = CTRL, up, resizeactive, 0 -60
bind = CTRL, down, resizeactive, 0 60

bind = CTRL ALT, Left,  movefocus, l
bind = CTRL ALT, Right, movefocus, r
bind = CTRL ALT, up, movefocus, u
bind = CTRL ALT, down, movefocus, d

bind = $mainMod, B, exec, $browser
bind = $mainMod, T, exec, swaync-client -t
bind = $mainMod, O, exec, $notes
bind = CTRL SHIFT, X , exec, $terminal
bind = $mainMod, R, exec, ~/.config/waybar/waybar.sh

bind = $mainMod, Q, killactive,

#bindm = $mainMod, mouse:272, movewindoes
bindm = $mainMod, mouse:273, resizewindows

bind = CTRL ALT, BackSpace, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, S, exec, $menu
bind = $mainMod, N, exec, kitty --hold sh -c "cat ~/.config/hypr/hyprland.conf | grep bind"
bind = $mainMod, R, exec, command -v pkill waybar && waybar,

###############
## AUTOSTART ##
###############

exec-once = waybar
exec-once = hyprpaper

cursor{
        invisible = false
}
