##############
## MONITORS ##
##############

###################
## LOOK AND FEEL ##
###################

#gaps_in = 2
#gaps_out = 10

####################
## variables/apps ##
####################

$moveto1 = command -v hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 1 && hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 2
$moveto2 = command -v hyprctl dispatch fucusmonitor HDMI-A-1 && hyprctl dispatch workspace 3 && hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 4 
$moveto3 = command -v hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 5 && hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 6
$moveto4 = command -v hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 7 && hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 8
$notes = obsidian
$mainMod = SUPER
$terminal = kitty
$imageEditor = gimp
$fileManager = dolphin
$menu = wofi
$browser = firefox


###############
## shortcuts ##
###############

#---workspace---
bind = $mainMod, 1, exec, $moveto1 
bind = $mainMod, 2, exec, $moveto2
bind = $mainMod, 3, exec, $moveto3
bind = $mainMod, 4, exec, $moveto4

#---window position---
#bind = $mainMod SHIFT, left, swapwindow, l
#bind = $mainMod SHIFT, right, swapwindow, r
#bind = $mainMod SHIFT, up, swapwindow, u
#bind = $mainMod SHIFT, down, swapwindow, d

bind = $mainMod SHIFT, right, exec, hyprctl dispatch movetoworkspace +2 
bind = $mainMod SHIFT, left, exec, hyprctl dispatch movetoworkspace -2

bind = $mainMod, left, movewindow, mon:+1
bind = $mainMod, right, movewindow, mon:-1

bind = CTRL, left, resizeactive, -60 0
bind = CTRL, right, resizeactive, 60 0
bind = CTRL, up, resizeactive, 0 -60
bind = CTRL, down, resizeactive, 0 60

bind = CTRL ALT, Left,  movefocus, l
bind = CTRL ALT, Right, movefocus, r
bind = CTRL ALT, up, movefocus, u
bind = CTRL ALT, down, movefocus, d

bind = $mainMod, B, exec, $browser

bind = $mainMod, O, exec, $notes
bind = CTRL SHIFT, x , exec, $terminal

bind = $mainMod, C, killactive,

bind = CTRL ALT, BackSpace, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, S, exec, $menu
bind = $mainMod, N, exec, kitty --hold sh -c "cat ~/.config/hypr/hyprland.conf | grep bind"
bind = $mainMod, R, exec, command -v pkill waybar && waybar,

exec-once = waybar
exec-once = hyprpaper

input {
	kb_layout = br
	kb_variant = abnt2
}

decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
    }
}
