###############
## shortcuts ##
###############

#---workspaces---
bind = $mainMod, 1, exec, $moveto1 
bind = $mainMod, 2, exec, $moveto2
bind = $mainMod, 3, exec, $moveto3
bind = $mainMod, 4, exec, $moveto4

#---window to workspace---
bind = $mainMod SHIFT, right, exec, hyprctl dispatch movetoworkspace +2
bind = $mainMod SHIFT, left, exec, hyprctl dispatch movetoworkspace -2

#---window to monitor---
bind = $mainMod SHIFT, right, exec, hyprctl dispatch movetoworkspace +2
bind = $mainMod SHIFT, left, exec, hyprctl dispatch movetoworkspace -2

#---window position---
#bind = $mainMod SHIFT, left, swapwindow, l
#bind = $mainMod SHIFT, right, swapwindow, r
#bind = $mainMod SHIFT, up, swapwindow, u
#bind = $mainMod SHIFT, down, swapwindow, d

#---resize window---
bind = CTRL, left, resizeactive, -60 0
bind = CTRL, right, resizeactive, 60 0
bind = CTRL, up, resizeactive, 0 -60
bind = CTRL, down, resizeactive, 0 60

#---change focus---
bind = CTRL ALT, Left,  movefocus, l
bind = CTRL ALT, Right, movefocus, r
bind = CTRL ALT, up, movefocus, u
bind = CTRL ALT, down, movefocus, d

#---apps---
bind = $mainMod, B, exec, $browser
bind = $mainMod, T, exec, swaync-client -t
bind = $mainMod, O, exec, $notes
bind = CTRL SHIFT, X , exec, $terminal
bind = $mainMod, R, exec, ~/.config/waybar/waybar.sh
bind = $mainMod, N, exec, $searchbar
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, S, exec, $menu
bind = $mainMod, D, exec, $launcher
bind = $mainMod, R, exec, command -v pkill waybar && waybar,

#---commands--
bind = $mainMod, Q, killactive,
bind = CTRL ALT, BackSpace, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, V, togglefloating
