####################
## variables/apps ##
####################

$moveto1 = command -v hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 1 && hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 2
$moveto2 = command -v hyprctl dispatch fucusmonitor eDP-1 && hyprctl dispatch workspace 3 && hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 4
$moveto3 = command -v hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 6 && hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 5
$moveto4 = command -v hyprctl dispatch focusmonitor eDP-1 && hyprctl dispatch workspace 7 && hyprctl dispatch focusmonitor HDMI-A-1 && hyprctl dispatch workspace 8
$notes = obsidian
$mainMod = SUPER
$terminal = kitty
$imageEditor = gimp
$fileManager = dolphin
$menu = pkill ~/.config/rofi/launcher.sh || bash ~/.config/rofi/launcher.sh
$searchbar = pkill ~/.config/rofi/commands/* || zsh ~/.config/rofi/dmenu/dmenu.sh
$launcher = rofi
$browser = firefox
$noteBar = swaync
